/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RentService } from "../rent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RentCreateInput } from "./RentCreateInput";
import { Rent } from "./Rent";
import { RentFindManyArgs } from "./RentFindManyArgs";
import { RentWhereUniqueInput } from "./RentWhereUniqueInput";
import { RentUpdateInput } from "./RentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RentControllerBase {
  constructor(
    protected readonly service: RentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rent })
  @nestAccessControl.UseRoles({
    resource: "Rent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRent(@common.Body() data: RentCreateInput): Promise<Rent> {
    return await this.service.createRent({
      data: {
        ...data,

        house: data.house
          ? {
              connect: data.house,
            }
          : undefined,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,

        house: {
          select: {
            id: true,
          },
        },

        id: true,
        paymentDate: true,
        status: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Rent] })
  @ApiNestedQuery(RentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Rent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rents(@common.Req() request: Request): Promise<Rent[]> {
    const args = plainToClass(RentFindManyArgs, request.query);
    return this.service.rents({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,

        house: {
          select: {
            id: true,
          },
        },

        id: true,
        paymentDate: true,
        status: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rent(
    @common.Param() params: RentWhereUniqueInput
  ): Promise<Rent | null> {
    const result = await this.service.rent({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        dueDate: true,

        house: {
          select: {
            id: true,
          },
        },

        id: true,
        paymentDate: true,
        status: true,

        tenant: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRent(
    @common.Param() params: RentWhereUniqueInput,
    @common.Body() data: RentUpdateInput
  ): Promise<Rent | null> {
    try {
      return await this.service.updateRent({
        where: params,
        data: {
          ...data,

          house: data.house
            ? {
                connect: data.house,
              }
            : undefined,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,

          house: {
            select: {
              id: true,
            },
          },

          id: true,
          paymentDate: true,
          status: true,

          tenant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRent(
    @common.Param() params: RentWhereUniqueInput
  ): Promise<Rent | null> {
    try {
      return await this.service.deleteRent({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          dueDate: true,

          house: {
            select: {
              id: true,
            },
          },

          id: true,
          paymentDate: true,
          status: true,

          tenant: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
