/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { RentListRelationFilter } from "../../rent/base/RentListRelationFilter";
import { TenantListRelationFilter } from "../../tenant/base/TenantListRelationFilter";

@InputType()
class HouseWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  address?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isOccupied?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  numberOfRooms?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RentListRelationFilter)
  @IsOptional()
  @Field(() => RentListRelationFilter, {
    nullable: true,
  })
  rents?: RentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TenantListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TenantListRelationFilter)
  @IsOptional()
  @Field(() => TenantListRelationFilter, {
    nullable: true,
  })
  tenants?: TenantListRelationFilter;
}

export { HouseWhereInput as HouseWhereInput };
